-- FitSync v7 Production Supabase schema
-- Run this once in Supabase SQL Editor.

create table if not exists public.fit_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'FitSync User',
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.fit_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (char_length(event_type) between 1 and 80),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.fit_profiles enable row level security;
alter table public.fit_events enable row level security;

drop policy if exists "users can read own profile" on public.fit_profiles;
drop policy if exists "users can insert own profile" on public.fit_profiles;
drop policy if exists "users can update own profile" on public.fit_profiles;
create policy "users can read own profile" on public.fit_profiles for select to authenticated using (auth.uid() = id);
create policy "users can insert own profile" on public.fit_profiles for insert to authenticated with check (auth.uid() = id);
create policy "users can update own profile" on public.fit_profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "users can read own events" on public.fit_events;
drop policy if exists "users can insert own events" on public.fit_events;
create policy "users can read own events" on public.fit_events for select to authenticated using (auth.uid() = user_id);
create policy "users can insert own events" on public.fit_events for insert to authenticated with check (auth.uid() = user_id);

create index if not exists fit_events_user_created_idx on public.fit_events(user_id, created_at desc);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.fit_profiles(id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'name','FitSync User'))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Keep the public client limited to authenticated rows.
revoke all on table public.fit_profiles from anon;
revoke all on table public.fit_events from anon;
grant select,insert,update on table public.fit_profiles to authenticated;
grant select,insert on table public.fit_events to authenticated;
